* * * TEST * * *

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -74,51 +74,52 @@ jobs:
           - v1.18.15
           - v1.17.11
     steps:
-      - uses: actions/setup-go@v1
-        with:
-          go-version: 1.16
-          github-token: ${{ github.token }}
-      - name: Set go env
-        run: |
-          echo GOPATH=$GITHUB_WORKSPACE >> $GITHUB_ENV
-          echo GO111MODULE=on >> $GITHUB_ENV
-          echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
-      - uses: actions/checkout@v2
-        with:
-          path: ${{ github.workspace }}/src/github.com/${{ github.repository }}
-      - uses: engineerd/setup-kind@v0.5.0
-        with:
-          config: src/github.com/${{ github.repository }}/${{matrix.image <= 'v1.19.11' && 'cluster-config-old.yaml' || 'cluster-config.yaml'}}
-          version: v0.11.1
-          image: kindest/node:${{ matrix.image }}
-          wait: ""
+#      - uses: actions/setup-go@v1
+#        with:
+#          go-version: 1.16
+#          github-token: ${{ github.token }}
+#      - name: Set go env
+#        run: |
+#          echo GOPATH=$GITHUB_WORKSPACE >> $GITHUB_ENV
+#          echo GO111MODULE=on >> $GITHUB_ENV
+#          echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
+#      - uses: actions/checkout@v2
+#        with:
+#          path: ${{ github.workspace }}/src/github.com/${{ github.repository }}
+#      - uses: engineerd/setup-kind@v0.5.0
+#        with:
+#          config: src/github.com/${{ github.repository }}/${{matrix.image <= 'v1.19.11' && 'cluster-config-old.yaml' || 'cluster-config.yaml'}}
+#          version: v0.11.1
+#          image: kindest/node:${{ matrix.image }}
+#          wait: ""
       - name: Setup Calico VPP CNI
         run: |
-          kubectl apply -f https://raw.githubusercontent.com/Bolodya1997/vpp-dataplane/nsm-new/yaml/generated/calico-vpp-kind.yaml
-          kubectl -n kube-system rollout status deploy/calico-kube-controllers
-          kubectl -n kube-system rollout status daemonset/calico-node
-      - name: Check kind cluster
-        run: |
-          kubectl version
-          kubectl cluster-info
-          kubectl get pods -n calico-vpp-dataplane
-          kubectl get pods -n kube-system
-          echo "current-context:" $(kubectl config current-context)
-          echo "environment-kubeconfig:" ${KUBECONFIG}
-        working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
-      - name: Integration tests
-        run: |
-          TESTS="${TESTS}|Heal/"
-          TESTS="${TESTS}|Feature/Test[^MN].*[^f]$"
-          TESTS="${TESTS}|Basic/Test[^M].*[^f]$"
-          TESTS="${TESTS}|Memory/Test[^M].*[^f]$"
-          go test -count 1 -timeout 40m -race -v ./... -run "${TESTS}"
-        env:
-          ARTIFACTS_DIR: ${{ matrix.image }}-logs/${{ matrix.image }}
-        working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
-      - name: Upload artifacts
-        if: ${{ success() || failure() || cancelled() }}
-        uses: actions/upload-artifact@v2
-        with:
-          name: Containers logs
-          path: ${{ github.workspace }}/src/github.com/${{ github.repository }}/${{ matrix.image }}-logs
+          cat /proc/cpuinfo
+#          kubectl apply -f https://raw.githubusercontent.com/Bolodya1997/vpp-dataplane/nsm-new/yaml/generated/calico-vpp-kind.yaml
+#          kubectl -n kube-system rollout status deploy/calico-kube-controllers
+#          kubectl -n kube-system rollout status daemonset/calico-node
+#      - name: Check kind cluster
+#        run: |
+#          kubectl version
+#          kubectl cluster-info
+#          kubectl get pods -n calico-vpp-dataplane
+#          kubectl get pods -n kube-system
+#          echo "current-context:" $(kubectl config current-context)
+#          echo "environment-kubeconfig:" ${KUBECONFIG}
+#        working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
+#      - name: Integration tests
+#        run: |
+#          TESTS="${TESTS}|Heal/"
+#          TESTS="${TESTS}|Feature/Test[^MN].*[^f]$"
+#          TESTS="${TESTS}|Basic/Test[^M].*[^f]$"
+#          TESTS="${TESTS}|Memory/Test[^M].*[^f]$"
+#          go test -count 1 -timeout 40m -race -v ./... -run "${TESTS}"
+#        env:
+#          ARTIFACTS_DIR: ${{ matrix.image }}-logs/${{ matrix.image }}
+#        working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
+#      - name: Upload artifacts
+#        if: ${{ success() || failure() || cancelled() }}
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: Containers logs
+#          path: ${{ github.workspace }}/src/github.com/${{ github.repository }}/${{ matrix.image }}-logs
